### ISSUE TITLE
Estructura de nombres

### ISSUE THREAD

**Issue by risturiz** [MaptimeBogota/ColombianJosmValidator#3]
Estoy resolviendo una nota y me encuentro con este warning:

> Los nombres de vias no deben contener abreviaturas, y deben seguir la estructura de nombre

La via en cuestión se define como: "la Dorada - San Miguel"

Desde mi completo desconocimiento para identificar los nombres, este es un warning válido?

(Nota #2830132)

**Comment by angoca** [comment]
Pero en este caso falta la palabra "Vía", o algo similar: Vía La Dorada - San Miguel

**Comment by risturiz** [comment]
Perfecto, entonces debe comenzar con la palabra "Vía"
