### ISSUE TITLE
highway = unclassified

### ISSUE THREAD

**Issue by risturiz** [MaptimeBogota/ColombianJosmValidator#4]
Que hacemos con todas estas vías? Cual es la manera de abordar esta validación de la forma mas eficiente?... Maproulette?

**Comment by angoca** [comment]
De acuerdo totalmente. Voy a organizar este desafío para corregir Colombia. Le voy a escribir a la comunidad en Telegram, para notificarlos que vamos a hacer este cambio masivo.

**Comment by risturiz** [comment]
Está interesante el validador, creo que seria buen tema ampliarlo en la próxima reunión

**Comment by angoca** [comment]
Las vías unclassified por uso actual, son las vías de menor categoría de para vehículos. Se deben dejar así, si realmente son inferiores a tertiary.
Si es una vía de tipo desconocido, si es un error, y debería cambiarse a road.
